config/routes.rb
Langweb::Application.routes.draw do
  resources :types


  resources :posts


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "语言文字规范", root_path, class: "brand" %>
<ul class="nav">
  <li><%= link_to "首 页", root_path %></li>
  <% Type.all.each do |t| %>
  <li><%= link_to t.name, type_path(t) %></li>
  <% end %>
</ul>

<ul class="pull-right nav">
  <% if user_signed_in? %>
    <li><%= link_to '管 理', posts_path %></li>
    <li><%= link_to '注 销', destroy_user_session_path, :method=>'delete' %></li>
  <% else %>
    <li><%= link_to '登 录', new_user_session_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Langweb" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Langweb" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/type_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "语言文字规范" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Langweb" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <style type="text/css" media="all">
      body { padding-top: 60px; }
      footer { margin: 25px auto; padding-top: 15px; border-top: 1px solid #ccc;}
    </style>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <footer><p>&copy;<%= Time.now.year %> 西溪小学</p></footer>
  </body>
</html>